-- tables
create table tw_access_token (id bigint not null auto_increment, version bigint not null, date_created datetime not null, name varchar(255) not null, user_id bigint not null, token varchar(255) not null, last_used datetime, primary key (id)) engine=InnoDB;
create table tw_process_progress (id bigint not null auto_increment, version bigint not null, process varchar(255) not null, workflow_id bigint not null, progress_pending bigint not null, progress_succeeded bigint not null, progress_failed bigint not null, progress_running bigint not null, progress_cached bigint not null, progress_submitted bigint not null, primary key (id)) engine=InnoDB;
create table tw_role (id bigint not null auto_increment, version bigint not null, authority varchar(255) not null, primary key (id)) engine=InnoDB;
create table tw_task (id bigint not null auto_increment, version bigint not null, rss bigint, env varchar(255), start datetime, script varchar(255), native_id bigint, time varchar(255), cpus integer, syscw bigint, read_bytes bigint, scratch varchar(255), container varchar(255), write_bytes bigint, process varchar(255), queue varchar(255), workflow_id bigint not null, task_id bigint not null, vol_ctxt bigint, exit_status bigint, disk bigint, pcpu double precision, module varchar(255), duration bigint, attempt integer, realtime bigint, complete datetime, submit datetime, rchar bigint, vmem bigint, workdir varchar(255), pmem double precision, name varchar(255) not null, syscr bigint, memory bigint, peak_rss bigint, peak_vmem bigint, status varchar(255) not null, hash varchar(255) not null, wchar bigint, error_action varchar(255), tag varchar(255), inv_ctxt bigint, primary key (id)) engine=InnoDB;
create table tw_user (id bigint not null auto_increment, version bigint not null, first_name varchar(255), auth_time datetime not null, organization varchar(255), user_name varchar(255) not null, last_name varchar(255), description varchar(255), email varchar(255) not null, auth_token varchar(255) not null, avatar varchar(255), primary key (id)) engine=InnoDB;
create table tw_user_role (id bigint not null auto_increment, version bigint not null, role_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table tw_workflow (id bigint not null auto_increment, version bigint not null, start datetime not null, profile varchar(255) not null, work_dir varchar(255) not null, container varchar(255) not null, commit_id varchar(255) not null, repository varchar(255) not null, container_engine varchar(255), user_name varchar(255) not null, owner_id bigint not null, session_id varchar(255) not null, error_report longtext, script_id varchar(255) not null, exit_status varchar(255), command_line varchar(255) not null, success bit, project_name varchar(255) not null, script_name varchar(255) not null, duration bigint, project_dir varchar(255) not null, complete datetime, home_dir varchar(255) not null, submit datetime not null, error_message varchar(255), script_file varchar(255) not null, launch_dir varchar(255) not null, run_name varchar(255) not null, config_files longtext, revision varchar(255) not null, params longtext, resume bit, manifest_nextflow_version varchar(255), manifest_default_branch varchar(255), manifest_home_page varchar(255), manifest_gitmodules varchar(255), manifest_description varchar(255), manifest_name varchar(255), manifest_author varchar(255), manifest_main_script varchar(255), nextflow_build varchar(255), nextflow_timestamp datetime, stats_compute_time_fmt varchar(255), stats_cached_count integer, stats_cached_duration bigint, stats_failed_duration bigint, stats_succeed_duration bigint, stats_failed_count integer, stats_cached_pct float, stats_cached_count_fmt varchar(255), stats_succeed_count_fmt varchar(255), stats_failed_pct float, stats_failed_count_fmt varchar(255), stats_ignored_count integer, stats_ignored_count_fmt varchar(255), stats_succeed_pct float, stats_succeed_count integer, stats_ignored_pct float, primary key (id)) engine=InnoDB;
create table tw_workflow_metrics (id bigint not null auto_increment, version bigint not null, process varchar(255) not null, workflow_id bigint not null, writes_q2 float, writes_max_label varchar(255), writes_q3label varchar(255), writes_q1 float, writes_q3 float, writes_max float, writes_min_label varchar(255), writes_min float, writes_mean float, writes_q1label varchar(255), writes_q2label varchar(255), time_q2 float, time_max_label varchar(255), time_q3label varchar(255), time_q1 float, time_q3 float, time_max float, time_min_label varchar(255), time_min float, time_mean float, time_q1label varchar(255), time_q2label varchar(255), reads_q2 float, reads_max_label varchar(255), reads_q3label varchar(255), reads_q1 float, reads_q3 float, reads_max float, reads_min_label varchar(255), reads_min float, reads_mean float, reads_q1label varchar(255), reads_q2label varchar(255), cpu_q2 float, cpu_max_label varchar(255), cpu_q3label varchar(255), cpu_q1 float, cpu_q3 float, cpu_max float, cpu_min_label varchar(255), cpu_min float, cpu_mean float, cpu_q1label varchar(255), cpu_q2label varchar(255), cpu_usage_q2 float, cpu_usage_max_label varchar(255), cpu_usage_q3label varchar(255), cpu_usage_q1 float, cpu_usage_q3 float, cpu_usage_max float, cpu_usage_min_label varchar(255), cpu_usage_min float, cpu_usage_mean float, cpu_usage_q1label varchar(255), cpu_usage_q2label varchar(255), vmem_q2 float, vmem_max_label varchar(255), vmem_q3label varchar(255), vmem_q1 float, vmem_q3 float, vmem_max float, vmem_min_label varchar(255), vmem_min float, vmem_mean float, vmem_q1label varchar(255), vmem_q2label varchar(255), mem_usage_q2 float, mem_usage_max_label varchar(255), mem_usage_q3label varchar(255), mem_usage_q1 float, mem_usage_q3 float, mem_usage_max float, mem_usage_min_label varchar(255), mem_usage_min float, mem_usage_mean float, mem_usage_q1label varchar(255), mem_usage_q2label varchar(255), time_usage_q2 float, time_usage_max_label varchar(255), time_usage_q3label varchar(255), time_usage_q1 float, time_usage_q3 float, time_usage_max float, time_usage_min_label varchar(255), time_usage_min float, time_usage_mean float, time_usage_q1label varchar(255), time_usage_q2label varchar(255), mem_q2 float, mem_max_label varchar(255), mem_q3label varchar(255), mem_q1 float, mem_q3 float, mem_max float, mem_min_label varchar(255), mem_min float, mem_mean float, mem_q1label varchar(255), mem_q2label varchar(255), primary key (id)) engine=InnoDB;
create table tw_workflow_tasks_progress (id bigint not null auto_increment, version bigint not null, workflow_id bigint not null, progress_pending bigint not null, progress_succeeded bigint not null, progress_failed bigint not null, progress_running bigint not null, progress_cached bigint not null, progress_submitted bigint not null, primary key (id)) engine=InnoDB;

-- indexes
create index nxd_token_user_name on tw_access_token (name, user_id);

-- unique keys
alter table tw_access_token add constraint UK43d3f7e9a0e95d8585e8d28ba7ba unique (user_id, name);
alter table tw_access_token add constraint UK_9qicn90sccoapoo2l77e5x2nv unique (token);
alter table tw_role add constraint UK_l9qajil33pku3v939nk3lgb8v unique (authority);
alter table tw_task add constraint UKffa4e2b65f434c9ce926bd7ae9f0 unique (workflow_id, task_id);
alter table tw_user add constraint UK_4arnwe454ok0t0qe0ik19shdg unique (user_name);
alter table tw_user add constraint UK_2onv3nihia5wv49sl5sxqnqsc unique (email);
alter table tw_user add constraint UK_7uosyj2m35578w7x9f2ef1qqs unique (auth_token);
alter table tw_workflow add constraint UKf0e09a4cfd0bd57e01075514d46c unique (session_id, run_name);

-- foreign keys
alter table tw_access_token add constraint FKst2ppktjejjhoet6fa7o2hagu foreign key (user_id) references tw_user (id);
alter table tw_process_progress add constraint FKp1og8dvye5iphxawf2gf3xg50 foreign key (workflow_id) references tw_workflow (id);
alter table tw_task add constraint FK7uo04bnq4ke6qy9p18ntsykjm foreign key (workflow_id) references tw_workflow (id);
alter table tw_user_role add constraint FK2m4irqu3461tkju8cq6yxte7s foreign key (role_id) references tw_role (id);
alter table tw_user_role add constraint FK61lvogpqcqbgsulgtpxf1x9gl foreign key (user_id) references tw_user (id);
alter table tw_workflow add constraint FKafu9pobh9ddf3pf56hpsjqpqd foreign key (owner_id) references tw_user (id);
alter table tw_workflow_metrics add constraint FKkh4gnu2v9idjbrolw6w1fwrtf foreign key (workflow_id) references tw_workflow (id);
alter table tw_workflow_tasks_progress add constraint FKt3q0yj7evdhijrhcf9t2yuqh6 foreign key (workflow_id) references tw_workflow (id);
